language: python
python:
  - "3.6"
# command to install dependencies
cache: pip
before_install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python tests/cube_ds_unittest.py